# syntax=docker/dockerfile:1

FROM node as base
WORKDIR /blog-client
COPY ./client/b-client ./
RUN npm install

FROM base as dev
EXPOSE 3000
ENTRYPOINT ["npm", "run" ,"dev"]

FROM base as build
RUN npm run build

FROM node as prod
COPY --from=build /blog-client/.output ./.output
ENTRYPOINT ["node" ,".output/server/index.mjs"]
