server:
  port: 8000

spring:
  application:
    name: blog
  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    url: ${MYSQL_URL:jdbc:mysql://localhost/blog?serverTimezone=Asia/Shanghai}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
