name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to aliyun server
        uses: appleboy/ssh-action@master@1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          username: ${{ secrets.REMOTE_USER }}
          script: |
            cd ~
            git clone https://github.com/chinesecooly/CICD-Blog.git
            cd ~/CICD-Blog
            docker compose -d --profile prod up


