name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to tencent server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST}}
          key: ${{ secrets.SERVER_SSH_KEY }}
          username: ${{ secrets.REMOTE_USER }}
          script: |
            # 切换到主目录
            cd ~ || exit
            # 判断是否安装了Docker，如果没有则使用官方提供的脚本安装Docker
            if ! command -v docker &> /dev/null ; then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
            fi
            # 判断是否拉拉取了代码，没有拉取则拉取
            if [ ! -d "./blog" ]; then
              git clone https://github.com/chinesecooly/blog.git
            fi
            # 进入工作目录
            cd blog || exit
            # 更新代码
            git pull
            # 构建前端代码
            cd nginx/templates/b-client 
            npm install 
            npm run build
            # 运行prod环境下的构建，并且每次都重新构建镜像
            docker compose --profile prod up -d --build
            # 重启nginx容器，更新配置文件
            docker container restart nginx



