name: Deploy
on:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy app with Docker Compose
        uses: docker/compose-action@v3
        with:
          context: .
          compose-file: docker-compose.yml
          project-name: blog
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          command: up -d

